# This file lists all the virtual machines that will be used in the redis cluster setup
VAGRANTFILE_API_VERSION="2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do | config |

    config.vm.box = "hashicorp/bionic64"
    config.ssh.insert_key = "false"
    config.ssh.password = "vagrant"

    # we can sysnc any file from  the host machine and 
    config.vm.synced_folder "." "/vagrant", disabled: true

    # The default provider is virtualbox . this can be configured to meet the needs
    # allocate the machine memory and cpu based on the available resources available on your machine
    config.vm.provider "vmware" do | machine |

        machine.memory = 512
        machine.cpus = 1

        # This settings is used to enable configuring clones with the same resource properties
        machine.linked_clone = true 
    end

    # This tutorial uses three master machines each having two replicas: This is to avoid brain split 
    # incase any of the machines drops from the cluster
    # Each of the machines would have a static ip address preconfigured so as to make it easier to work with 
    # ansible


    # master 0, am zero indexed 
    
    (0..2).each do |i|

        config.vm.define "master#{i}" do | master |
            master.vm.hostname = "redis-cluster-tutorial.master#{i}"
            master.vm.network "private_network", ip: "192.168.58.#{i+2}"
        end
    end 


    (0..7).each do |i|

        config.vm.define "replica#{i}" do | replica |
            replica.vm.hostname = "redis-cluster-tutorial.replica#{i}"
            replica.vm.network "private_network", ip: "192.168.58.#{i+5}"
        end
    end
end