---
# tasks file for cluster-setup

- name: configure server keys
  file:
    path: /etc/ssl/private
    owner: "{{ owner_and_group_name }}"
    group: "{{ owner_and_group_name }}"
    mode: "u+rwx,g+x" 

- name: install redis service
  tags: service
  template:
    src: redis.service.j2
    dest: /etc/systemd/system/redis.service

  notify: 
    - Daemon reload
    - Run Redis 
