---

- name: Copy Issuing Certificate to Server
  copy:
    src: ca.crt
    dest: /usr/local/share/ca-certificates/ca.crt

- name: Copy CA key to the Server
  copy:
    src: ca.key
    dest: /etc/ssl/private/ca.key


- name: Generate Redis Server Certificate and Keys
  tags: server, certgen
  shell: >
    cd /tmp && openssl genrsa -out redis.key 2048 && \
    openssl req -new -sha256 -key redis.key \
    -subj "/O=RedisLabs/CN=Production Server Certificate" | \
    openssl x509 -req -sha256 \
    -CA /usr/local/share/ca-certificates/ca.crt \
    -CAkey /etc/ssl/private/ca.key \
    -CAcreateserial \
    -days 365 \
    -out redis.crt && \
    mv redis.key /etc/ssl/private/ && \
    mv redis.crt /etc/ssl/


- name: Generate Client Certificate and Key
  tags: client, certgen, permissions
  shell: >
    cd /tmp && openssl genrsa -out client.key 2048 && \
    openssl req -new -sha256 -key client.key \
    -subj "/O=RedisLabs/CN=Redis Client Certificate" | \
    openssl x509 -req -sha256 \
    -CA /usr/local/share/ca-certificates/ca.crt \
    -CAkey /etc/ssl/private/ca.key \
    -CAcreateserial \
    -days 365 \
    -out client.crt && \
    mv client.* /etc/ssl/ && \
    chown ubuntu:ubuntu /etc/ssl/* && \
    chmod 640 /etc/ssl/*

- name: Permissions Setup
  tags: permissions
  shell: >
    chown ubuntu:ubuntu /etc/ssl/*.crt && \
    chmod 644 /etc/ssl/*.crt && \
    chown ubuntu:ubuntu /etc/ssl/private/redis.key

- name: CA Permissions Setup
  tags: permissions ca
  shell: >
    chown ubuntu:ubuntu /usr/local/share/ca-certificates/ca.crt && \
    chmod 644 /usr/local/share/ca-certificates/ca.crt 

- name: Update system certificates
  shell: update-ca-certificates

