---
- name: Generate Issuing Certificate and Key
  tags: ca, certgen
  shell: >
    cd "{{ tmp_dir }}" && openssl genrsa -out "{{ tls_ca_key }}" 4096 && \
    openssl req -x509 -new -nodes -sha256 \
    -key "{{ tls_ca_key }}"
    -days "{{ tls_ca_exp_days }}"
    -subj "{{ tls_ca_subj }}"
    -out "{{ tls_ca_cert }}" && \
    mv "{{ tls_ca_key }}" "{{ tls_key_dir }}" && \
    mv "{{ tls_ca_cert }}" "{{ tls_ca_cert_dir }}"

- name: Generate Redis Server Certificate and Keys
  tags: server, certgen
  shell: >
    cd "{{ tmp_dir }}" && openssl genrsa -out "{{ tls_server_key }}" 2048 && \
    openssl req -new -sha256 -key "{{ tls_server_key }}" \
    -subj "{{ tls_server_subj }}" | \
    openssl x509 -req -sha256 \
    -CA "{{ tls_ca_cert_dir }}/{{ tls_ca_cert }}" \
    -CAkey "{{ tls_key_dir }}/{{ tls_ca_key }}" \
    -CAcreateserial \
    -days "{{ tls_cert_exp_days }}" \
    -out "{{ tls_server_cert }}" && \
    mv "{{ tls_server_key }}" "{{ tls_key_dir }}" && \
    mv "{{ tls_server_cert }}" "{{ tls_cert_dir }}"

- name: Generate Client Certificate and Key
  tags: client, certgen
  shell: >
    cd "{{ tmp_dir }}" && openssl genrsa -out "{{ tls_client_key }}" 2048 && \
    openssl req -new -sha256 -key "{{ tls_client_key }}" \
    -subj "{{ tls_client_subj }}" | \
    openssl x509 -req -sha256 \
    -CA "{{ tls_ca_cert_dir }}/{{ tls_ca_cert }}" \
    -CAkey "{{ tls_key_dir }}/{{ tls_ca_key }}" \
    -CAcreateserial \
    -days "{{ tls_cert_exp_days }}" \
    -out "{{ tls_client_cert }}" && \
    mv client.* "{{ tls_cert_dir }}" && \
    chown "{{ owner }}":"{{ group }}" "{{tls_cert_dir}}" && \
    chmod 640 "{{ tls_cert_dir }}"

- name: Permissions Setup
  shell: >
    chown "{{ redis_sys_user }}":"{{ redis_sys_group }}" "{{ tls_cert_dir }}"/*.crt && \
    chmod 640 "{{ tls_cert_dir }}"/*.crt

- name: CA Permissions Setup
  shell: >
    chown "{{ redis_sys_user }}":"{{ redis_sys_group }}" "{{ tls_ca_cert_dir}}/{{ tls_ca_cert }}"
    chmod 644 "{{ tls_ca_cert_dir}}/{{ tls_ca_cert }}"

- name: Update system certificates
  shell: update-ca-certificates

