---
# tasks file for install-redis

- name: Installing Dependencies
  tags: always
  apt:
    name:
      - build-essential
      - tcl
      - tcl-tls
      - redis-tools
      - libssl-dev
      - libsystemd-dev
    state: present
    update_cache: yes


- name: Logging DIR
  tags: setup
  file:
    path: "{{ redis_log_dir }}"
    state: directory
    owner: "ubuntu"
    group: "ubuntu"
    mode: "0770"
    force: yes

- name: Logging file Permissions
  tags: permissions, setup
  file:
    path: "{{ redis_log_dir }}/{{ redis_log_file }}"
    state: touch
    owner: "ubuntu"
    group: "ubuntu"
    mode: "0640"

- name: Download Redis
  tags: download,setup
  ansible.builtin.unarchive:
    src: "{{ redis_download_url }}"
    dest: /tmp
    remote_src: yes


- name: Install redis
  tags: build, setup
  community.general.make:
    chdir: /tmp/redis-stable
    target: install
    params: 
      BUILD_TLS: "yes"
      USE_SYSTEMD: "yes"

- name: Change /etc/redis ownership
  file:
    path: /etc/redis
    owner: ubuntu
    group: ubuntu
    mode: "u+rwx,g+x"
    recurse: yes

- name: Configure redis
  tags: configure, setup
  template:
    src: redis.conf.j2
    dest: /etc/redis/redis.conf
    



