---
- hosts: all
  become: yes
  tasks:
    - name: Stop The server node
      systemd:
        name: redis
        state: stopped

    - name: Delete Log files
      file:
        path: "/var/log/redis/redis.log"
        state: absent


    - name: Delete node config file
      file:
        path: "/etc/redis/node.conf"
        state: absent

    - name: Start the server 
      systemd:
        name: redis
        state: started


